energywebfoundation/ssi

apps/nestjs-wallet/docs/issuance-tutorial.md, apps/nestjs-wallet/docs/openapi.json, apps/nestjs-wallet/src/elia-exchange/elia-exchange.controller.ts, apps/nestjs-wallet/src/vc-api/exchanges/types/vp-request-interact-service-type.ts, apps/nestjs-wallet/src/vc-api/vc-api.controller.ts
Issuance tutorial updated to reflect the latest VC API exchanges spec and generic VC API configuration approach
=> docs: update issuance tutorial for new exchange flow

apps/nestjs-wallet/src/vc-api/exchanges/dtos/callback-configuration.dto.spec.ts, apps/nestjs-wallet/src/vc-api/exchanges/dtos/callback-configuration.dto.ts, apps/nestjs-wallet/src/vc-api/exchanges/dtos/vp-request-interact-service.dto.spec.ts, apps/nestjs-wallet/src/vc-api/exchanges/dtos/vp-request-interact-service.dto.ts
=> feat: allow localhost in URLs

apps/nestjs-wallet/src/vc-api/credentials/credentials.service.spec.ts, apps/nestjs-wallet/src/vc-api/credentials/dtos/credential.dto.ts, apps/nestjs-wallet/src/vc-api/credentials/dtos/presentation.dto.ts, apps/nestjs-wallet/src/vc-api/exchanges/dtos/exchange-definition.dto.spec.ts, apps/nestjs-wallet/src/vc-api/exchanges/dtos/vp-request-presentation-defintion-query.dto.ts, apps/nestjs-wallet/src/vc-api/exchanges/types/credential.ts, apps/nestjs-wallet/src/vc-api/exchanges/types/presentation.ts, apps/nestjs-wallet/test/app.e2e-spec.ts, apps/nestjs-wallet/test/did/did.e2e-suite.ts, apps/nestjs-wallet/test/vc-api/credentials/vc-api.e2e-suite.ts, apps/nestjs-wallet/test/vc-api/exchanges/rebeam/rebeam-cpo-node.ts, apps/nestjs-wallet/test/vc-api/exchanges/rebeam/rebeam-supplier.ts, apps/nestjs-wallet/test/vc-api/exchanges/rebeam/rebeam.e2e-suite.ts, apps/nestjs-wallet/test/vc-api/exchanges/resident-card/resident-card-issuance.exchange.ts, apps/nestjs-wallet/test/vc-api/exchanges/resident-card/resident-card-presentation.exchange.ts, apps/nestjs-wallet/test/vc-api/exchanges/resident-card/resident-card.e2e-suite.ts, apps/nestjs-wallet/tsconfig.json
initial passing rebeam e2e test
- Includes reorg of e2e tests
- @context now accomodates objects (in addition to strings)
=> initial rebeam presentation definition

apps/nestjs-wallet/src/vc-api/credentials/dtos/credential.dto.ts, apps/nestjs-wallet/src/vc-api/exchanges/dtos/vp-request-query.dto.ts, apps/nestjs-wallet/src/vc-api/exchanges/entities/transaction.entity.spec.ts, apps/nestjs-wallet/src/vc-api/exchanges/entities/transaction.entity.ts, apps/nestjs-wallet/src/vc-api/exchanges/types/credential.ts, apps/nestjs-wallet/src/vc-api/exchanges/types/verifiable-credential.ts, apps/nestjs-wallet/test/vc-api/exchanges/rebeam/rebeam-cpo-node.ts, apps/nestjs-wallet/test/vc-api/exchanges/rebeam/rebeam.e2e-suite.ts
Add validation for incoming verifiable presentation against presentation request definition.
=> feat(vc-api): validate incoming presentation

apps/vc-api/src/vc-api/credentials/credentials.service.spec.ts
Fix chargingCredential context
=> Iva 9/rebeam sign charging data

apps/vc-api/src/setup.ts
=> enable cors

apps/vc-api/docs/openapi.json, apps/vc-api/docs/tutorials/resident-card-tutorial.md, apps/vc-api/docs/vc-api.postman_environment.json, apps/vc-api/src/setup.ts, apps/vc-api/test/vc-api/exchanges/resident-card/resident-card.e2e-suite.ts
The main changes are in [resident-card-tutorial.md](https://github.com/energywebfoundation/ssi/compare/chore/IVA-17/tutorial-with-add-review?expand=1#diff-2a79e8048ca42486628d9c4957113fce38cc16473556ff42e7d983a6d8fef16c)
Updated the resident-card-tutorial to use the new mediated and `add review` functionality
=> Chore/iva 17/tutorial with add review

apps/vc-api/src/vc-api/exchanges/exchange.service.ts
Otherwise no log is seen from failed request
=> fix(exchange.service): log callback error

apps/vc-api/docs/tutorials/resident-card-tutorial.md, apps/vc-api/src/vc-api/exchanges/entities/transaction.entity.spec.ts, apps/vc-api/src/vc-api/exchanges/entities/transaction.entity.ts
Includes:
- code change to send callbacks after presentation submission
- use of Post Test Server in resident card tutorial
=> Feat/iva 25/callback in tutorial

Dockerfile
- Making this pr just to share an idea on how to possibly fix build
=> fix: add setup to create home directory - attempt to fix build fail

devops/ssi-helm/templates/deployment.yaml, devops/ssi-helm/values-dev.yaml, devops/ssi-helm/values-sandbox.yaml, devops/ssi-helm/values.yaml
https://energyweb.atlassian.net/browse/IVA-13 
- Add BASE_URL value to helm charts
=> chore: add helm chart values for base url

apps/vc-api/docs/tutorials/resident-card-tutorial.md
=> docs(resident-card): change elia-exchange to vc-api

apps/vc-api/docs/tutorials/did-key-export.md, apps/vc-api/src/did/did.service.spec.ts, apps/vc-api/src/did/did.service.ts, apps/vc-api/src/key/dtos/key-description.dto.ts, apps/vc-api/src/key/dtos/key-pair.dto.ts, apps/vc-api/src/key/key.controller.spec.ts, apps/vc-api/src/key/key.controller.ts, apps/vc-api/src/key/key.module.ts, apps/vc-api/src/key/key.service.spec.ts, apps/vc-api/src/key/key.service.ts, apps/vc-api/test/app.e2e-spec.ts, apps/vc-api/test/key/key.e2e-suite.ts, apps/vc-api/test/wallet-client.ts
Can import&export a key and export a key generated from a DID (see [key.e2e-suite.ts](https://github.com/energywebfoundation/ssi/pull/75/files#diff-11dae5e3c1d9565f9a72061aae79b99df6f857e8c0b708e6bf758b382ca285eb) )
Can also generate a DID from an imported key
=> Key import/key

apps/vc-api/src/vc-api/credentials/dtos/verify-presentation.dto.ts, apps/vc-api/src/vc-api/vc-api.controller.ts
https://energyweb.atlassian.net/browse/IVA-45
- Add presentations/verify endpoint to vc-api controller
=> feat: add presentations/verify endpoint to vc-api controller

apps/vc-api/README.md
Adding existing endpoints in the endpoint table
=> docs(README): update endpoint table with verification

apps/vc-api/docs/exchanges.md, apps/vc-api/docs/tutorials/resident-card-tutorial.md, apps/vc-api/src/vc-api/exchanges/dtos/exchange-definition.dto.spec.ts, apps/vc-api/src/vc-api/exchanges/dtos/transaction.dto.ts, apps/vc-api/src/vc-api/exchanges/dtos/vp-request.dto.ts, apps/vc-api/src/vc-api/exchanges/exchange.service.spec.ts, apps/vc-api/src/vc-api/exchanges/exchange.service.ts, apps/vc-api/test/vc-api/exchanges/resident-card/resident-card-issuance.exchange.ts, apps/vc-api/test/vc-api/exchanges/resident-card/resident-card.e2e-suite.ts
This PR:
- Adds documentation of callback functionality
- Fixes DTO conversion of `TransactionEntity`
- Validates TransactionDTO before sending as notification
=> Docs/iva 55/document callback functionality

apps/vc-api/docs/api-versioning.md, apps/vc-api/src/setup.ts
This PR implements a basis for having REST API endpoints versioned.
=> feat: api versioning

.github/workflows/main.yml
This PR implements caching of downloaded packages that should decrease CI build times.
=> feat: CI rush caching

apps/credential-from-input-descriptor/package.json, apps/credential-from-input-descriptor/src/index.ts, apps/vc-api/package.json, apps/vc-api/src/index.ts, common/config/rush/pnpm-lock.yaml, rush.json, tests/e2e/.eslintignore, tests/e2e/.eslintrc.js, tests/e2e/package.json, tests/e2e/src/main-suite.e2e-spec.ts, tests/e2e/tsconfig.json
This PR adds a monorepo project containing a comprehensive test suite for testing interoperability between monorepo projects.
=> tests: e2e test suite

apps/vc-api/src/key/key.controller.ts
- Remove some unused imports
- Add license header
- Add "key" tag to controller
=> docs(vc-api): add key tag to key.controller

apps/credential-from-input-descriptor/docs/openapi.json, apps/credential-from-input-descriptor/package.json, apps/credential-from-input-descriptor/scripts/write-open-api-json.ts, apps/credential-from-input-descriptor/src/main.ts, apps/credential-from-input-descriptor/src/setup.ts, apps/credential-from-input-descriptor/tsconfig.json
This PR:
* commits `docs/openapi.json` swagger file
* adds `apps/credential-from-input-descriptor/scripts/write-open-api-json.ts` script that updates the above
=> feat(credential-from-input-descriptor): openapi file generation script
