- README.md
- apps/nestjs-wallet/package.json
- apps/nestjs-wallet/src/vc-api/exchanges/dtos/callback-configuration.dto.ts
- apps/nestjs-wallet/src/vc-api/exchanges/dtos/exchange-definition.dto.ts
- apps/nestjs-wallet/src/vc-api/exchanges/entities/exchange.entity.ts
- apps/nestjs-wallet/src/vc-api/exchanges/entities/transaction.entity.spec.ts
- apps/nestjs-wallet/src/vc-api/exchanges/entities/transaction.entity.ts
- apps/nestjs-wallet/src/vc-api/exchanges/exchange.service.spec.ts
- apps/nestjs-wallet/src/vc-api/exchanges/exchange.service.ts
- apps/nestjs-wallet/src/vc-api/exchanges/types/callback-configuration.ts
- apps/nestjs-wallet/src/vc-api/vc-api.module.ts
- apps/nestjs-wallet/test/app.e2e-spec.ts
- apps/nestjs-wallet/test/wallet-client.ts
- common/config/rush/pnpm-lock.yaml
Rebeam Jira issue: https://energyweb.atlassian.net/browse/REBDEV-74
> feat: add callback to exchange configuration

- apps/nestjs-wallet/src/vc-api/exchanges/dtos/vp-request-query.dto.ts
- apps/nestjs-wallet/src/vc-api/exchanges/entities/exchange.entity.spec.ts
- apps/nestjs-wallet/src/vc-api/exchanges/entities/exchange.entity.ts
- apps/nestjs-wallet/src/vc-api/exchanges/entities/transaction.entity.ts
- apps/nestjs-wallet/src/vc-api/exchanges/exchange.service.ts
This tightens the consistency boundary around the exchange entity.
Exchange entity is no longer mutated as when starting exchange.
So there is no need to save exchange (so no potential need for a db transaction).
> feat(exchange.entity): generate txId in constructor

- apps/nestjs-wallet/src/vc-api/exchanges/dtos/custom-validators/presentation-definition-credential-query.validator.ts
- apps/nestjs-wallet/src/vc-api/exchanges/dtos/exchange-definition.dto.spec.ts
- apps/nestjs-wallet/src/vc-api/exchanges/dtos/exchange-definition.dto.ts
- apps/nestjs-wallet/src/vc-api/exchanges/dtos/vp-request-did-auth-query.dto.ts
- apps/nestjs-wallet/src/vc-api/exchanges/dtos/vp-request-interact.dto.ts
- apps/nestjs-wallet/src/vc-api/exchanges/dtos/vp-request-presentation-defintion-query.dto.spec.ts
- apps/nestjs-wallet/src/vc-api/exchanges/dtos/vp-request-presentation-defintion-query.dto.ts
- apps/nestjs-wallet/src/vc-api/exchanges/dtos/vp-request-query.dto.ts
- apps/nestjs-wallet/src/vc-api/exchanges/entities/exchange.entity.ts
- apps/nestjs-wallet/src/vc-api/exchanges/exchange.service.spec.ts
- apps/nestjs-wallet/src/vc-api/exchanges/exchange.service.ts
- apps/nestjs-wallet/test/app.e2e-spec.ts
- apps/nestjs-wallet/test/sample-business-logic/resident-card-issuance.exchange.ts
- apps/nestjs-wallet/test/sample-business-logic/resident-card-presentation.exchange.ts
Main changes are:
- Add `IsPresentationDefinitionCredentialQuery` custom validator (which uses `@sphereon/pex`)
- Fix nested validation in `exchange-definition.dto` (needed to add `@Type`)
> refactor: move Presention Definition validation to custom validator

- apps/nestjs-wallet/src/vc-api/credentials/credentials.service.ts
- apps/nestjs-wallet/src/vc-api/credentials/dtos/verification-result.dto.ts
- apps/nestjs-wallet/src/vc-api/credentials/types/verification-result.ts
- apps/nestjs-wallet/src/vc-api/exchanges/dtos/presentation-submission.dto.ts
- apps/nestjs-wallet/src/vc-api/exchanges/dtos/transaction.dto.ts
- apps/nestjs-wallet/src/vc-api/exchanges/entities/presentation-submission.entity.ts
- apps/nestjs-wallet/src/vc-api/exchanges/entities/transaction.entity.spec.ts
- apps/nestjs-wallet/src/vc-api/exchanges/entities/transaction.entity.ts
- apps/nestjs-wallet/src/vc-api/exchanges/exchange.service.spec.ts
- apps/nestjs-wallet/src/vc-api/exchanges/exchange.service.ts
- apps/nestjs-wallet/src/vc-api/vc-api.controller.ts
- apps/nestjs-wallet/src/vc-api/vc-api.module.ts
- apps/nestjs-wallet/test/vc-api/exchanges/rebeam/rebeam.e2e-suite.ts
There is currently this callback feature so that verifiers can be notified when their configured exchange is done. Instead of sending in the callback the `ExchangeResponse` that is sent the holder/presenter, sending a `TransactionDto` as this has more detailed information for the verifier.
TODO:
> Feat/iva 4/send callback result

- devops/ssi-helm/values-dev.yaml
As the database is in memory per pod, the app cannot horizontally scale
> fix: reduce replicaCount to 1 in dev

- apps/vc-api/src/vc-api/exchanges/dtos/get-transaction.dto.ts
- apps/vc-api/src/vc-api/vc-api.controller.ts
- apps/vc-api/test/vc-api/exchanges/resident-card/resident-card.e2e-suite.ts
- apps/vc-api/test/wallet-client.ts
This adds a (non-standard, not included in https://w3c-ccg.github.io/vc-api/) endpoint to allow for querying of an exchange transaction. 
I'm basing my notion of "exchange transactions" from the continue exchange endpoint of vc-api https://w3c-ccg.github.io/vc-api/#continue-exchange
This endpoint is needed for the "query outstanding presentations to review" step of a mediated exchange https://github.com/energywebfoundation/ssi#credential-presentationissuance
> feat(vc-api): add getTransaction endpoint

- apps/vc-api/docs/tutorials/resident-card-tutorial.md
- apps/vc-api/test/vc-api/exchanges/resident-card/resident-card-presentation.exchange.ts
VC-API has a "Resident Card" tutorial. The “Resident Card” presentation definition was not correctly ask for a credential of type "PermanentResidentCard". This PR fixes that.
> fix(res-card): ask for type in pres def

- apps/vc-api/src/did/did.service.ts
- apps/vc-api/src/vc-api/credentials/credentials.service.spec.ts
- apps/vc-api/src/vc-api/credentials/credentials.service.ts
- apps/vc-api/src/vc-api/credentials/dtos/authenticate.dto.ts
- apps/vc-api/src/vc-api/credentials/dtos/issue-options.dto.ts
- apps/vc-api/src/vc-api/credentials/dtos/prove-presentation-options.dto.ts
- apps/vc-api/src/vc-api/credentials/dtos/prove-presentation.dto.ts
- apps/vc-api/test/vc-api/credential.service.spec.data.ts
- apps/vc-api/test/vc-api/credential.service.spec.key.ts
- apps/vc-api/test/vc-api/credentials/vc-api.e2e-suite.ts
- apps/vc-api/test/vc-api/exchanges/rebeam/rebeam-supplier.ts
- apps/vc-api/test/vc-api/exchanges/rebeam/rebeam.e2e-suite.ts
- apps/vc-api/test/vc-api/exchanges/resident-card/resident-card-issuance.exchange.ts
- apps/vc-api/test/vc-api/exchanges/resident-card/resident-card.e2e-suite.ts
The VC-API spec changed to not allow `type`, `verificationMethod` and `proofPurpose` anymore for issueCredential and so this is removed from our implementation https://github.com/w3c-ccg/vc-api/pull/263/files
Prove presentation options still have the properties though so this PR separate the issuance options from presentation proof options.
> removing verification method

- apps/vc-api/README.md
- apps/vc-api/docs/tutorials/key-export-import-tutorial.md
- apps/vc-api/src/did/did.controller.spec.ts
- apps/vc-api/src/did/did.controller.ts
- apps/vc-api/src/did/dto/create-did-options.dto.ts
- apps/vc-api/src/did/types/did-method.ts
- apps/vc-api/src/key/dtos/key-description.dto.ts
- apps/vc-api/test/key/key.e2e-suite.ts
- apps/vc-api/test/wallet-client.ts
Can register a did:key with a key known to the server. See https://github.com/energywebfoundation/ssi/blob/feat/IVA-30/register-did-with-keyid/apps/vc-api/docs/tutorials/key-export-import-tutorial.md#22-register-did for example
> feat(did): register DID with keyId

- apps/vc-api/docs/openapi.json
- apps/vc-api/docs/tutorials/resident-card-tutorial.md
- apps/vc-api/src/vc-api/exchanges/dtos/exchange-response.dto.ts
- apps/vc-api/src/vc-api/exchanges/entities/transaction.entity.ts
- apps/vc-api/src/vc-api/exchanges/exchange.service.ts
- apps/vc-api/src/vc-api/vc-api.controller.ts
- apps/vc-api/test/vc-api/exchanges/rebeam/rebeam.e2e-suite.ts
- apps/vc-api/test/vc-api/exchanges/resident-card/resident-card.e2e-suite.ts
- apps/vc-api/test/wallet-client.ts
Return in continue exchange endpoint a 202 status code with
`retry-after` header when a review has not been sent. Hardocde retry
after value to 5 seconds.
> feat: return 202 status code on continue exchange

- apps/vc-api/package.json
- common/config/rush/pnpm-lock.yaml
This PR fixes errors displayed by Webstorm when editing files from the `apps/vc-api` folder caused by `@rushstack/eslint-config` not included in the `app/vp-api` dev dependencies.
> fix: fixing eslint not working in Webstorm

- apps/vc-api/src/vc-api/exchanges/exchange.service.spec.ts
- apps/vc-api/src/vc-api/exchanges/exchange.service.ts
- apps/vc-api/test/app.e2e-spec.ts
This PR adds logic to the `POST /vc-api/exchanges` endpoint to respond with "409 Conflict" response when submitting exchangeId already used.
TODO:
> feat: POST /vc-api/exchanges "409 Conflict" response when collision detected

- apps/vc-api/package.json
- common/config/rush/pnpm-lock.yaml
This PR upgrades dependencies and freezes the version of the `@nestjs/typeorm` to avoid breaking tests when the lockfile is updated.
Motivation: safer to work on up-to-date dependencies when implementing API versioning.
> chore: upgrading dependencies

- apps/vc-api/package.json
- common/config/rush/pnpm-lock.yaml
- libraries/did/package.json
- libraries/webkms/package.json
This PR solves incompatibility issues of @rushstack/eslint-config v2.3 with eslint v8
> chore: upgrading @rushstack/eslint-config to v2.6

- apps/vc-api/package.json
- apps/vc-api/src/app.module.ts
- common/config/rush/pnpm-lock.yaml
This PR fixes the following example `vc-api` application error log messages showing repeatedly:
```text
[Nest] 3306  - 07/23/2022, 10:50:18 AM   ERROR [ExceptionsHandler] ENOENT: no such file or directory, stat '/Users/artur/WebstormProjects/energyweb/iam/ssi/apps/vc-api/static-assets/.well-known/index.html'
Error: ENOENT: no such file or directory, stat '/Users/artur/WebstormProjects/energyweb/iam/ssi/apps/vc-api/static-assets/.well-known/index.html'
```
> fix: fixing error log message written, when `/` path accessed

- apps/credential-from-input-descriptor/Dockerfile
This PR fixes CI broken after adding the `tests/e2e` project. The reason is that the `test/e2e/package.json` file is not copied when the "Converter" image is built.
> fix: fixing CI broken 

- apps/vc-api/docs/openapi.json
Update open-api def to use `v1` version string.
We should automate this updating as a precommit hook on vc-api
> chore(vc-api): update openapi def with versions

- apps/vc-api/src/setup.ts
- apps/vc-api/src/vc-api/exchanges/exchange.service.ts
- apps/vc-api/test/app.e2e-spec.ts
- apps/vc-api/test/vc-api/credentials/vc-api.e2e-suite.ts
- apps/vc-api/test/wallet-client.ts
- devops/ssi-helm/values-dev.yaml
- devops/ssi-helm/values-sandbox.yaml
This PR:
* fixes `.vpRequest.interact.service[0].serviceEndpoint` value in `/v1/vc-api/exchanges/{exchangeId}` response not having API version prefix
* fixes VC-API E2E tests application instance not having API version set to 1
* defines one `API_DEFAULT_VERSION_PREFIX` constant to define the default API version for both runtime and tests
* adjusts `BASE_URL` deployments settings to not include API path version prefix
> fix: adding missing version prefix in url generated by API endpoints

- apps/credential-from-input-descriptor/tsconfig.json
This PR fixes ESLint errors thrown for the files in the tests folder
> fix(input-desc-to-cred): fixing ESLint errors 

- apps/credential-from-input-descriptor/Dockerfile
- apps/credential-from-input-descriptor/src/main.ts
- apps/vc-api/src/main.ts
This PR displays a license on the applications start. The message content is taken from the `license-header.txt` file from the repository root
> feat: displaying a license on start
